config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]

  scope '(:locale)', locale: /fr|en/ do
    resources :categories do
      resources :works
    end
    resources :calendars
    resources :static_pages, only: [:show], path: 'page', param: :id


    get '/a-propos', to: 'pages#a_propos', as: 'a_propos'
    get '/contact', to: 'pages#contact', as: 'contact'
    root to: "pages#home"
  end

  # Define your other routes here

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :work
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :works
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
  validates :title_fr, :title_en, :content_fr, :content_en, presence: true
  def to_param
    "#{id}-#{title_fr.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  has_many_attached :photos
  belongs_to :category
  has_many :calendars, dependent: :destroy # Supprime les calendars liés automatiquement
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @calendars = Calendar.order(date_start: :desc).all
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @works = Work.where(category_id: @category.id).order(year: :desc)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @contact = Contact.find(params[:id])
    @categories = Category.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def a_propos
    @categories = Category.all
  end

  def contact
    @categories = Category.all
  end
  def home
    @works = Work.all
    @categories = Category.all
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    @static_page = StaticPage.find(params[:id]) # Rails extrait l'ID avant le premier tiret

    @categories = Category.all
    @page = StaticPage.find_by(id: params[:id])
    unless @page
      render plain: "Page introuvable", status: :not_found
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  def show
    @work = Work.find(params[:id])
    @category = @work.category
    @categories = Category.all
    @works = Work.where(category_id: @category.id).order(year: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calendars/index.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

    <nav role="navigation" class="menu offmobile">
  <ul>
      <% @categories.each_with_index do |categorie, index| %>

          <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>

<div class="menu-listing w-100 w-md-75">
  <%= link_to t('lien_agenda'), root_path, class: "link-logo" %>
  <div class="sous-menu">
    <% years = @calendars.map { |calendar| calendar.date_start.year }.uniq.sort_by { |year| -year } %>
      <% years.each do |year| %>
      <h3 style="margin-top:1.5rem; font-size:1rem"><%= year %></h3>
         <% @calendars.select { |calendar| calendar.date_start.year == year }.each do |calendar| %>
  <div class="row">
  <% if calendar.work %>
    <div class="col-md-3 col-8">
      <% if calendar.name.present? %>
        <% if I18n.locale == :fr %>
          <%= link_to calendar.name, [calendar.work.category, calendar.work], class: "link-calendar" %>
        <% else %>
          <%= link_to calendar.name, [calendar.work.category, calendar.work], class: "link-calendar" %>
        <% end %>
      <% else %>
        <% if I18n.locale == :fr %>
          <%= link_to calendar.work.name_fr, [calendar.work.category, calendar.work], class: "link-calendar" %>
        <% else %>
          <%= link_to calendar.work.name_en, [calendar.work.category, calendar.work], class: "link-calendar" %>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="col-md-3 col-8">
      <%= calendar.name %>
    </div>
  <% end %>
  <div class="col-md-2 col-4 text-md-start text-end"><%= calendar.date_start.strftime("%d.%m.%Y") %></div>
  <div class="col-md-7 col-12"><%= calendar.place %></div>
</div>

        <% end %>
     <% end %>
   </div>
</div>

app/views/categories/show.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

    <nav role="navigation" class="menu offmobile">
   <ul>
      <% @categories.each_with_index do |categorie, index| %>

          <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>


        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>

<%= render 'shared/menu_listing' %>

app/views/contacts/index.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

    <nav role="navigation" class="menu offmobile">
    <ul>
      <% @categories.each_with_index do |categorie, index| %>
           <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to "Agenda", calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->
        <li><%= link_to categorie.name, category_path(categorie), class: "link-menu" %></li>
      <% end %>


      <!-- Lien "Contact" -->
      <li><%= link_to "A propos", a_propos_path, class:"link-menu" %></li>
      <li><%= link_to "Contact", contact_path, class:"link-menu" %></li>
      <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>

<div class="menu-listing w-100 w-md-75">
  <%= link_to "Contact", root_path, class: "link-logo" %>
  <div class="sous-menu">
    <div class="my-3">
      <h4 style="font-weight:bold">Daphné Biiga Nwanak &amp; Baudouin Woehl</h4>
      <span>+33 6 98 51 54 52 / +33 6 08 32 93 17</span><br>
      <span><a href="mailto:daphnebaudouin.contact@gmail.com" class="mail-contact">daphnebaudouin.contact[at]gmail.com</a></span>
    </div>

    <div class="my-3">
      <h4 style="font-weight:bold">Palabres Palabres</h4>
      <span>Association loi 1901</span><br>
      <span>Siège social : 24 rue de Rilly la Montage 51100 REIMS</span><br>
      <span>Siret : 91197832800019</span><br>
      <span>APE : 9001Z</span><br>
      <span>Licence d’entrepreneur de spectacle : PLATESV-D-2022-004331</span><br>
      <span>Présidente : Juliette Bebin</span>
    </div>
    <div class="my-3">
      <h4 style="font-weight:bold">Conception du site</h4>
      <span>Charles Woehl</span><br>
      <span><a href="https://www.charleswoehl.fr" target=blank class="mail-contact">www.charleswoehl.fr</a></span>
    </div>
   </div>
</div>

app/views/contacts/show.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

    <nav role="navigation" class="menu offmobile">
  <ul>
      <% @categories.each_with_index do |categorie, index| %>
           <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>
<div class="menu-listing w-100 w-md-75">
  <%= link_to t('lien_contact'), root_path, class: "link-logo" %>
  <div class="sous-menu">
  <div class="my-3">
    <h4>Daphné Biiga Nwanak &amp; Baudouin Woehl</h4>
    <span>+33 6 98 51 54 52 / +33 6 08 32 93 17</span><br>
    <span><a href="mailto:daphnebaudouin.contact@gmail.com" class="mail-contact">daphnebaudouin.contact[at]gmail.com</a></span>
  </div>

  <div class="my-3">
    <h4 style="font-weight:bold">Palabres Palabres</h4>
    <span><%= t('association') %></span><br>
    <span><%= t('address') %></span><br>
    <span><%= t('siret') %></span><br>
    <span><%= t('ape') %></span><br>
    <span><%= t('license') %></span><br>
    <span><%= t('president') %></span>
  </div>
  <div class="my-3">
    <h4 style="font-weight:bold"><%= t('conception') %></h4>
    <span>Charles Woehl</span><br>
    <span><a href="https://www.charleswoehl.fr" target=blank class="mail-contact">www.charleswoehl.fr</a></span>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DAPHNÉ - BAUDOUIN </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
   </body>
</html>

app/views/pages/a_propos.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

  <nav role="navigation" class="menu offmobile">
   <ul>
      <% @categories.each_with_index do |categorie, index| %>
           <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
</header>

<div class="menu-listing w-100 w-md-75">
  <%= link_to t('lien_a_propos'), root_path, class: "link-logo" %>
  <div class="sous-menu">
    <div class="my-3 w-100 w-md-75">
      <p style="text-indent: 20px;"><%= t('apropos1') %></p>
      <p style="text-indent: 20px;"><%= t('apropos2') %></p>
      <p style="text-indent: 20px;"><%= t('apropos3') %></p>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

    <nav role="navigation" class="menu offmobile">
  <ul>
      <% @categories.each_with_index do |categorie, index| %>
           <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>
<div class="menu-listing w-100 w-md-75">
  <%= link_to t('lien_contact'), root_path, class: "link-logo" %>
  <div class="sous-menu">
  <div class="my-3">
    <h4>Daphné Biiga Nwanak &amp; Baudouin Woehl</h4>
    <span>+33 6 98 51 54 52 / +33 6 08 32 93 17</span><br>
    <span><a href="mailto:daphnebaudouin.contact@gmail.com" class="mail-contact">daphnebaudouin.contact[at]gmail.com</a></span>
  </div>

  <div class="my-3">
    <h4 style="font-weight:bold">Palabres Palabres</h4>
    <span><%= t('association') %></span><br>
    <span><%= t('address') %></span><br>
    <span><%= t('siret') %></span><br>
    <span><%= t('ape') %></span><br>
    <span><%= t('license') %></span><br>
    <span><%= t('president') %></span>
  </div>
  <div class="my-3">
    <h4 style="font-weight:bold"><%= t('conception') %></h4>
    <span>Charles Woehl</span><br>
    <span><a href="https://www.charleswoehl.fr" target=blank class="mail-contact">www.charleswoehl.fr</a></span>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

   <nav role="navigation" class="menu">
   <ul>
       <% @categories.each_with_index do |categorie, index| %>

          <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>


        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>

 <div class="menu-listing-home">
  <div class="pic-home top-115">
    <img src='https://res.cloudinary.com/dss64lrxx/image/upload/v1708693872/development/8eozmoecfz8ayvhkkmaa67worbf8.jpg' width="100%">
   </div>
</div>

app/views/shared/_header.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    DAPHNE BAUDOUIN
  <% end %>

    <nav role="navigation" class="menu">
    <ul>
      <% @categories.each_with_index do |categorie, index| %>
           <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to "Agenda", calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->
        <li><%= link_to categorie.name, category_path(categorie), class: "link-menu" %></li>
      <% end %>


      <!-- Lien "Contact" -->
      <li><%= link_to "A propos", a_propos_path, class:"link-menu" %></li>
      <li><%= link_to "Contact", contact_path, class:"link-menu" %></li>
      <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>

app/views/shared/_media.html.erb
<hr>
<h3>Photo actuelle</h3>
<% if model.photos.attached? %>
  <div class="photos-container">
    <% model.photos.each do |photo| %>
      <div class="photo-preview">
        <%= cl_image_tag(photo.key, width: 500, style: "object-fit: cover; width: 500px; margin: 10px;") %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_menu_listing.html.erb
<div class="menu-listing">
  <% if I18n.locale == :fr %>
    <%= link_to @category.name_fr,root_path, class: "link-logo"   %>
  <% else %>
    <%= link_to @category.name_en,root_path, class: "link-logo"   %>
  <% end %>
  <div class="sous-menu">
    <ul>
      <% @works.each do |work| %>
        <li>
           <% if I18n.locale == :fr %>
          <%= link_to work.name_fr, [work.category, work], class: "link-sous-menu" %>
    <% else %>
          <%= link_to work.name_en, [work.category, work], class: "link-sous-menu" %>
    <% end %>
           <div class="year-mini"><%= work.year %></div>
        </li>
      <% end %>
      <li>
  </div>
</div>

app/views/static_pages/show.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

    <nav role="navigation" class="menu offmobile">
  <ul>
      <% @categories.each_with_index do |categorie, index| %>
           <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>

 <div class="menu-listing w-100 w-md-75">
  <%= link_to @page.title_fr, root_path, class: "link-logo" %>
 <div class="sous-menu">
 <% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new) %>
<div class="sous-menu">
  <% if I18n.locale == :fr %>
    <%= markdown.render(@page.content_fr).html_safe %>
  <% else %>
    <%= markdown.render(@page.content_en).html_safe %>
  <% end %>
</div>
</div>
</div>

app/views/works/show.html.erb
<header>
  <%= link_to root_path, {class: "link-logo"} do %>
    Daphné & Baudouin
  <% end %>

    <nav role="navigation" class="menu offmobile">
  <ul>
      <% @categories.each_with_index do |categorie, index| %>
           <!-- Insérer le lien "Agenda" à la deuxième position -->
          <li><%= link_to t('lien_agenda'), calendars_path, class:"link-menu" %></li>

        <!-- Afficher les autres catégories -->

        <% if I18n.locale == :fr %>
          <li><%= link_to categorie.name_fr, category_path(categorie), class: "link-menu" %></li>
        <% else %>
          <li><%= link_to categorie.name_en, category_path(categorie), class: "link-menu" %></li>
        <% end %>
      <% end %>


      <!-- Lien "Contact" -->
<li><%= link_to t('lien_a_propos'), static_page_path(StaticPage.find(2)), class: "link-menu" %></li>
<li><%= link_to t('lien_contact'), static_page_path(StaticPage.find(1)), class: "link-menu" %></li>
       <li class="mt-2"; style="font-size:14px"><%= link_to "FR", url_for(locale: 'fr'), class:"link-menu"  %> | <%= link_to "EN", url_for(locale: 'en'), class:"link-menu" %></li>
    </ul>
  </nav>
 </header>

<div class="menu-listing">
  <% if I18n.locale == :fr %>
    <%= link_to @category.name_fr, category_path(@category), class: "link-logo" %>
  <% else %>
    <%= link_to @category.name_en, category_path(@category), class: "link-logo" %>
  <% end %>
  <div class="sous-menu offmobile">
    <ul>
      <% @works.each do |work| %>
        <li>
          <% if I18n.locale == :fr %>
            <%= link_to work.name_fr, [work.category, work], class: "link-sous-menu" %>
          <% else %>
            <%= link_to work.name_en, [work.category, work], class: "link-sous-menu" %>
          <% end %>

           <div class="year-mini"><%= work.year %></div>
        </li>
      <% end %>
      <li>
  </div>
</div>
<div class="bloc-work">
  <h1>
    <% if I18n.locale == :fr %>
      <%= @work.name_fr %>
    <% else %>
      <%= @work.name_en %>
    <% end %>
    <div class="year-mini"><%= @work.year %></div>
  </h1>
  <h2>
        <% if I18n.locale == :fr %>

    <%= @work.sous_titre_fr %>
    <% else %>
    <%= @work.sous_titre_en %>
    <% end %>
    </h2>

<% if @work.photos.attached? %>
  <div class="photos-slider" data-controller="slider">
    <button class="slider-arrow left-arrow" data-action="click->slider#previous" aria-label="Précédent">&#10094;</button>
    <div class="slides" data-slider-target="slides">
      <% @work.photos.each_with_index do |photo, index| %>
        <div class="photo-item" data-index="<%= index %>">
          <%= cl_image_tag(photo.key, crop: :fill, width: 500, height: 300, class: "photo-preview") %>
        </div>
      <% end %>
    </div>
    <button class="slider-arrow right-arrow" data-action="click->slider#next" aria-label="Suivant">&#10095;</button>
  </div>
<% end %>



  <div class="description">
    <% require 'redcarpet' %>
    <% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new) %>
        <% if I18n.locale == :fr %>
    <%= markdown.render(@work.description_fr).html_safe %> <br>
    <% else %>
    <%= markdown.render(@work.description_en).html_safe %> <br>
    <% end %>
  </div>
</div>